[package]
name = "repository_application"
version = "0.1.0"
authors = ["Joshua Terrasas <joshua.terrasas@studentbody.byu.edu>"]
edition = "2018"

[dependencies]
uuid = { features = ["v4"] }
url = "*"
git2 = "*"
sqlx = { default-features = false, features = ["runtime-tokio", "macros", "mysql"] }
