version: "3"
services:
  web:
    build: ../airdrome_hud/
    ports:
      - "3000:3000"
    restart: unless-stopped
  api:
    build: ../airdrome_api/
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=$DATABASE_URL
    restart: unless-stopped
