[package]
name = "airdrome_api"
version = "0.1.0"
authors = ["Joshua Terrasas <joshua.terrasas@studentbody.byu.edu>"]
edition = "2018"

[dependencies]
actix-web = { version = "2.0", features=["openssl"] }
actix-rt = ""
openssl = ""
serde = ""
serde_json = ""
chrono = ""
uuid = { features = ["v4"] }
sqlx = { default-features = false, features = ["runtime-actix-native-tls", "macros", "mysql", "offline", "migrate"] }
obex = ""
zip = ""
log = ""
env_logger = ""
base64 = ""
sha-1 = ""
