[package]
name = "airdrome_api"
version = "0.1.0"
authors = ["Joshua Terrasas <joshua.terrasas@studentbody.byu.edu>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = ""
serde = ""
serde_json = ""
chrono = ""
uuid = { features = ["v4"] }
sqlx = { default-features = false, features = ["runtime-tokio", "macros", "mysql"] }
event_application = { path = "../applications/event_application" }
object_application = { path = "../applications/object_application" }
obex_application = { path = "../applications/obex_application" }
events_service = { path = "../services/events_service" }
